# Generated by Django 4.2.7 on 2023-11-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('digital services', 'digital services'), ('cosmetics and body care', 'cosmetics and body care'), ('food and beverage', 'food and beverage'), ('health and wellness', 'health and wellness'), ('household items', 'household items')], max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.product'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
